import { auth } from '../../../../../auth'
import { redirect } from 'next/navigation';
import type { Metadata } from "next"
import { siteConfig } from "@/app/siteConfig"

export const metadata: Metadata = {
  title: `${siteConfig.name} | Sign Out`,
  description: siteConfig.description,
  metadataBase: new URL("https://www.superfa.st/auth/signout"),
  alternates: { canonical: "/auth/signout" },
  keywords: [
    // Core Technologies
    "Next.js",
    "React",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Tailwind CSS",
    "CSS",
    "HTML",
    "Web Components",

    // Frameworks & Libraries
    "Next.js boilerplate",
    "React framework",
    "JavaScript framework",
    "UI framework",
    "Component library",
    "React hooks",
    "React components",
    "Redux",
    "Context API",

    // Development Concepts
    "Web development",
    "Frontend development",
    "Backend development",
    "Full-stack development",
    "Software development",
    "SaaS development",
    "API development",
    "RESTful API",
    "GraphQL",
    "Serverless",

    // Development Tools
    "Developer tools",
    "Development environment",
    "Code editor",
    "VS Code",
    "Git",
    "GitHub",
    "Version control",
    "CI/CD",
    "Docker",
    "Kubernetes",

    // Performance & Optimization
    "Performance optimization",
    "Code optimization",
    "Lazy loading",
    "Code splitting",
    "Bundle optimization",
    "Web performance",
    "Core Web Vitals",
    "Lighthouse",
    "Performance metrics",

    // SEO & Marketing
    "SEO optimization",
    "Search engine optimization",
    "Meta tags",
    "Structured data",
    "Schema markup",
    "Content marketing",
    "Digital marketing",
    "Analytics",
    "Google Analytics",

    // Product Features
    "Rapid development",
    "Developer productivity",
    "Production ready template",
    "Code boilerplate",
    "Starter kit",
    "SaaS starter kit",
    "Web application template",
    "Responsive design",
    "Mobile-first",
    "Progressive Web App",

    // Business & Startup
    "Startup development",
    "Startup tools",
    "MVP development",
    "Minimum viable product",
    "Product launch",
    "SaaS business",
    "Subscription model",
    "Revenue generation",
    "Business automation",

    // User Experience
    "User interface",
    "User experience",
    "UI/UX design",
    "Accessibility",
    "WCAG compliance",
    "Responsive design",
    "Mobile app",
    "Cross-platform",
    "Progressive enhancement",

    // Security & Compliance
    "Web security",
    "Authentication",
    "Authorization",
    "OAuth",
    "JWT",
    "Data protection",
    "GDPR compliance",
    "Privacy policy",
    "Terms of service",

    // Cloud & Hosting
    "Cloud hosting",
    "AWS",
    "Azure",
    "Google Cloud",
    "Vercel",
    "Netlify",
    "Deployment",
    "Continuous deployment",
    "Serverless functions",

    // Database & Storage
    "Database",
    "SQL",
    "NoSQL",
    "MongoDB",
    "PostgreSQL",
    "Firebase",
    "Supabase",
    "Data storage",
    "Data modeling",

    // Testing & Quality
    "Unit testing",
    "Integration testing",
    "End-to-end testing",
    "Jest",
    "React Testing Library",
    "Cypress",
    "Test automation",
    "Code quality",
    "Linting",

    // Competitors & Alternatives
    "Create React App",
    "Gatsby",
    "Remix",
    "Astro",
    "Nuxt.js",
    "Vue.js",
    "Svelte",
    "Angular",
    "Next.js alternatives",
    "React boilerplate",
    "React starter kit",
    "React template",
    "Next.js template",
    "Next.js starter",
    "Next.js starter kit",
    "Next.js boilerplate alternatives",
    "Vercel templates",
    "Netlify templates",
    "Jamstack",
    "JAMstack",

    // Indie Hackers & Small Startups
    "Ship Fast",
    "Shipfast",
    "Next Starter Pro",
    "T3 Stack",
    "Create T3 App",
    "Indie Stack",
    "Epic Stack",
    "Precedent",
    "Next Enterprise",
    "Next SaaS Starter",
    "Next Landing Page",
    "Next Dashboard",
    "Next Admin",
    "Next Commerce",
    "Next Blog",
    "Next Portfolio",
    "Next Auth Starter",
    "Next PWA Starter",
    "Next Stripe Starter",
    "Next Subscription Starter",
    "Indie Hacker Tools",
    "Bootstrapped SaaS",
    "Solo Founder Tools",
    "Micro SaaS Template",
    "SaaS Boilerplate",
    "SaaS in a Box",
    "SaaS Kit",
    "SaaS Framework",
    "No-code Alternative",
    "Low-code Platform",

    // Product Categories
    "SaaS Builder",
    "Website Builder",
    "App Builder",
    "Landing Page Builder",
    "Dashboard Builder",
    "Admin Panel Builder",
    "E-commerce Builder",
    "Blog Builder",
    "Portfolio Builder",
    "Membership Site Builder",
    "Subscription Site Builder",
    "Digital Product Platform",
    "Online Course Platform",
    "Community Platform",
    "Marketplace Builder",
    "API Builder",
    "Headless CMS",
    "Static Site Generator",
    "Full-stack Framework",
    "Serverless Framework",

    // Indie Platforms & Communities
    "Product Hunt",
    "Indie Hackers",
    "Gumroad",
    "Lemonsqueezy",
    "Buy Me a Coffee",
    "Ko-fi",
    "Patreon",
    "Open Collective",
    "GitHub Sponsors",
    "Dev.to",
    "Hashnode",
    "Micro Acquire",
    "Side Project Stack",
    "Weekend Build",
    "Build in Public",
    "Learn in Public",
    "No-code Movement",
    "Low-code Movement",
    "Maker Community",
    "Developer Community",

    // Startup Tools & Platforms
    "Vercel",
    "Netlify",
    "Railway",
    "Render",
    "Heroku",
    "DigitalOcean",
    "AWS Amplify",
    "Firebase",
    "Supabase",
    "PlanetScale",
    "Stripe",
    "Auth0",
    "Clerk",
    "NextAuth",
    "Prisma",
    "tRPC",
    "Tailwind UI",
    "Chakra UI",
    "Material UI",
    "Radix UI",
    "Shadcn UI",
    "DaisyUI",
    "Framer Motion",
    "React Query",
    "SWR",
    "Zustand",
    "React Hook Form",
    "Zod",
    "React Icons",
    "React Email",
    "React PDF",
    "React Charts",
    "React Tables",
    "React Maps",
    "React Calendar",
    "React Native",
    "Expo",
    "Electron",
    "Tauri",

    // Popular Stacks & Methodologies
    "MERN Stack",
    "MEAN Stack",
    "PERN Stack",
    "JAMstack",
    "T3 Stack",
    "Remix Stack",
    "Next.js Stack",
    "Full Stack",
    "Serverless Stack",
    "Headless Stack",
    "Cloud Native",
    "Progressive Web Apps",
    "Mobile First",
    "API First",
    "Design System",
    "Component Library",
    "Micro Frontend",
    "Micro Services",
    "Monorepo",
    "Monolith",
    "Composable Architecture",

    // Brand & Creator
    "SuperFast",
    "Kalash Vasaniya",
    "Developer tools",
    "Web application",
    "Software solution"
  ],
  authors: [
    {
      name: "Kalash Vasaniya",
      url: "https://bento.me/kalashvasaniya",
    },
  ],
  creator: "Kalash Vasaniya",
  publisher: "SuperFast",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: siteConfig.images,
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    images: siteConfig.images,
    creator: "@amikalash",
  },
  robots: {
    index: false,
    follow: false,
    googleBot: {
      index: false,
      follow: false,
      "max-image-preview": "none",
      "max-video-preview": 0,
      "max-snippet": 0,
      noimageindex: true,
    },
  },
  icons: {
    icon: '/favicon.ico', // Make sure you have a favicon.ico in public folder
    apple: '/apple-icon.png', // Make sure you have this in public folder
  }
}

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const session = await auth();

  if (!session) {
    redirect('/auth/signin');
  }

  return <main className="mx-auto max-w-6xl">{children}</main>
}
